@startuml

Actor User as u

participant "cheddar_cli.adb" as cli
participant "call_framework.adb" as cf
participant "call_scheduling_framework.adb" as csf
participant "priority_assignement-rm.adb" as pa

u -> cli : cheddar_cli \ \n  --file=example.xml  \ \n  --request=scheduling_set_priorities_according_to_rate_monotonic  \ \n --output=stdout_xml_analysis




cli -> cf : <b>sequential_framework_request</b>\n(system \n, requestTable \n, responseTable \n, output=>Xml_Output)



cf -> cf :<b>call_a_request</b> \n (system \n , request \n , a_response \n , Xml_Output)

note right
request contains
<b>scheduling_set_priorities_according_to_rate_monotonic</b>
statement
end note

cf -> csf : <b>set_priorities</b> \n ( system \n , a_response \n , request.target \n , scheduling_set_priorities_according_to_rate_monotonic \n , Xml_Output)

csf -> pa : <b>set_priority_according_to_rm</b> \n ( sys.tasks \n , a_processor.name)

pa --> csf : <b>sys.tasks</b> 
note right
the system tasks <b>priorities</b>
are set after the function call
end note

csf --> cf : a_response 
note left
response get added
to the <b>reponseTable</b>
end note

cf --> cli : reponseTable

cli --> u : responses

@enduml