all: 
	gnatmake -x -Pmemory_parser_writer.gpr 
clean:
	gnatclean -r -Pmemory_parser_writer.gpr
	rm -f output_parse_dram.xml
	rm -f output_parse_generic_memory.xml
	rm -f output_parse_kalray.xml
	rm -f output_write_dram.xml
	rm -f output_write_generic_memory.xml
	rm -f output_write_kalray.xml	
output_clean:
	rm -f memory_parser_writer_driver
	rm -f output_parse_dram.xml
	rm -f output_parse_generic_memory.xml
	rm -f output_parse_kalray.xml
	rm -f output_write_dram.xml
	rm -f output_write_generic_memory.xml
	rm -f output_write_kalray.xml	


