
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Convert_Strings;

with Convert_Unbounded_Strings;

with text_io;
use text_io;



Package MILS_Security is 
 
type MILS_Confidentiality_Level_Type is (
	UnClassified,
	Classified,
	Secret,
	Top_Secret);

procedure To_MILS_Confidentiality_Level_Type is
new Convert_Strings(MILS_Confidentiality_Level_Type, UnClassified);
procedure To_MILS_Confidentiality_Level_Type is
new Convert_Unbounded_Strings(MILS_Confidentiality_Level_Type, UnClassified);
function XML_String (obj : in MILS_Confidentiality_Level_Type) return Unbounded_String;
function XML_Ref_String (obj : in MILS_Confidentiality_Level_Type) return Unbounded_String;
package MILS_Confidentiality_Level_Type_io is new text_io.enumeration_io(MILS_Confidentiality_Level_Type);
use MILS_Confidentiality_Level_Type_io;


type MILS_Integrity_Level_Type is (
	Low,
	Medium,
	High);

procedure To_MILS_Integrity_Level_Type is
new Convert_Strings(MILS_Integrity_Level_Type, Low);
procedure To_MILS_Integrity_Level_Type is
new Convert_Unbounded_Strings(MILS_Integrity_Level_Type, Low);
function XML_String (obj : in MILS_Integrity_Level_Type) return Unbounded_String;
function XML_Ref_String (obj : in MILS_Integrity_Level_Type) return Unbounded_String;
package MILS_Integrity_Level_Type_io is new text_io.enumeration_io(MILS_Integrity_Level_Type);
use MILS_Integrity_Level_Type_io;


type MILS_Component_Type is (
	SLS,
	MSLS,
	MLS);

procedure To_MILS_Component_Type is
new Convert_Strings(MILS_Component_Type, SLS);
procedure To_MILS_Component_Type is
new Convert_Unbounded_Strings(MILS_Component_Type, SLS);
function XML_String (obj : in MILS_Component_Type) return Unbounded_String;
function XML_Ref_String (obj : in MILS_Component_Type) return Unbounded_String;
package MILS_Component_Type_io is new text_io.enumeration_io(MILS_Component_Type);
use MILS_Component_Type_io;


type MILS_Partition_Type is (
	Device,
	Application);

procedure To_MILS_Partition_Type is
new Convert_Strings(MILS_Partition_Type, Device);
procedure To_MILS_Partition_Type is
new Convert_Unbounded_Strings(MILS_Partition_Type, Device);
function XML_String (obj : in MILS_Partition_Type) return Unbounded_String;
function XML_Ref_String (obj : in MILS_Partition_Type) return Unbounded_String;
package MILS_Partition_Type_io is new text_io.enumeration_io(MILS_Partition_Type);
use MILS_Partition_Type_io;


type MILS_Task_Type is (
	Application,
	MMR,
	Guard,
	Collator,
	Downgrader,
	Upgrader);

procedure To_MILS_Task_Type is
new Convert_Strings(MILS_Task_Type, Application);
procedure To_MILS_Task_Type is
new Convert_Unbounded_Strings(MILS_Task_Type, Application);
function XML_String (obj : in MILS_Task_Type) return Unbounded_String;
function XML_Ref_String (obj : in MILS_Task_Type) return Unbounded_String;
package MILS_Task_Type_io is new text_io.enumeration_io(MILS_Task_Type);
use MILS_Task_Type_io;



End MILS_Security;
