
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Text_io;
use Text_io;

with unbounded_strings;
use unbounded_strings;

with primitive_xml_strings;
use primitive_xml_strings;



Package Body AADL_Parser_Interface is 
 

-- --------= Binding_Record_Type =--------

procedure Initialize(obj : out Binding_Record_Type) is 
begin
	obj.cpu_name := empty_string;
	obj.address_space_name := empty_string;
end Initialize;

procedure Put(obj : in Binding_Record_Type) is 
begin
	put("cpu_name: "); put(obj.cpu_name); put ( "; " );
	put("address_space_name: "); put(obj.address_space_name); put ( "; " );
end Put;
 
procedure Put(obj : in Binding_Record_Type_Ptr) is
begin
	Put(Obj.All);
end Put;


procedure Build_Attributes_XML_String(obj : in Binding_Record_Type; result : in out Unbounded_String) is 
begin
	if (XML_String(obj.cpu_name) /= Empty_String) then
		result := result & to_unbounded_string("<cpu_name>") & XML_String(obj.cpu_name) & to_unbounded_string("</cpu_name>");
	end if;
	if (XML_String(obj.address_space_name) /= Empty_String) then
		result := result & to_unbounded_string("<address_space_name>") & XML_String(obj.address_space_name) & to_unbounded_string("</address_space_name>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in Binding_Record_Type) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<binding_record_type>");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</binding_record_type>");
	return (result);
end XML_String;

function XML_String(obj : in Binding_Record_Type_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Binding_Record_Type) return Unbounded_String is
	result : Unbounded_String;
begin
	raise xml_ref_string_error;
	return to_unbounded_string("");
end XML_Ref_String;

function Copy ( obj : in Binding_Record_Type ) return Binding_Record_Type_Ptr is
	New_Binding_Record_Type : Binding_Record_Type_Ptr;
begin
	New_Binding_Record_Type := new Binding_Record_Type'(obj);
	return (New_Binding_Record_Type);
end Copy;

function Copy ( obj : in Binding_Record_Type_Ptr ) return Binding_Record_Type_Ptr is
begin
	return copy(obj.all);
end Copy;



End AADL_Parser_Interface;
