
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Text_io;
use Text_io;

with Unbounded_Strings;
use Unbounded_Strings;

use unbounded_strings.Unbounded_String_List_Package;

with Convert_Strings;

with Convert_Unbounded_Strings;

with Ada.Finalization;

with Unchecked_Deallocation;

with Primitive_XML_Strings;
use Primitive_XML_Strings;

with Tables;

with ada.strings.unbounded.text_io;
use ada.strings.unbounded.text_io;



Package AADL_Parser_Interface is 
 
type Binding_Record_Type; type Binding_Record_Type_Ptr is access all Binding_Record_Type;



-- --------= Binding_Record_Type =--------

type Binding_Record_Type is
record
 cpu_name : Unbounded_String;
 address_space_name : Unbounded_String;
end record;

procedure Initialize(obj : out Binding_Record_Type);
procedure Put(obj : in Binding_Record_Type);
procedure Put(obj : in Binding_Record_Type_Ptr);
function Copy(obj : in Binding_Record_Type_Ptr) return Binding_Record_Type_Ptr;
function Copy(obj : in Binding_Record_Type) return Binding_Record_Type_Ptr;
procedure Build_Attributes_XML_String(obj : in Binding_Record_Type; result : in out Unbounded_String);
function XML_String(obj : in Binding_Record_Type) return Unbounded_String;
function XML_String(obj : in Binding_Record_Type_Ptr) return Unbounded_String;
function XML_Ref_String(obj : in Binding_Record_Type) return Unbounded_String;
procedure Free  is new Unchecked_Deallocation (Binding_Record_Type, Binding_Record_Type_Ptr);

package Processor_Binding_Package is new Tables(Binding_Record_Type, Framework_Config.Max_Address_Spaces, Put, XML_String, XML_Ref_String);
use Processor_Binding_Package;
subtype Processor_Binding_Table is Processor_Binding_Package.table;
subtype Processor_Binding_Table_Ptr is  Processor_Binding_Package.table_Ptr;
subtype Processor_Binding_Range is Processor_Binding_Package.table_range;
subtype Processor_Binding_Range_Ptr is  Processor_Binding_Package.table_range_Ptr;


End AADL_Parser_Interface;
