------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
--
--  Any modification of this file will be lost.
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model.
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Cheddar is a free real time scheduling tool.
-- This program provides services to automatically check temporal constraints
-- of real time tasks.
--
-- Copyright (C) 2002-2009   Frank Singhoff
-- Cheddar is developed by the LAB-STICC Team, University of Brest
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--      To post to this mailing list, you must be subscribed
--      (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

with Framework_Config; use Framework_Config;

with id_generators; use id_generators;

with Text_IO; use Text_IO;

with unbounded_strings; use unbounded_strings;

use unbounded_strings.unbounded_string_list_package;

with convert_strings;

with convert_unbounded_strings;

with standards_io; use standards_io;

use standards_io.boolean_io;

with Ada.Finalization;

with Unchecked_Deallocation;

with primitive_xml_strings; use primitive_xml_strings;

with access_lists;

with Ada.Strings.Unbounded.Text_IO; use Ada.Strings.Unbounded.Text_IO;

with systems; use systems;

package applicability_constraints_main_structure is

   type applicability_constraint_function is access function
     (context : system) return Boolean;

-- --------= Applicability_Constraint =--------

   type applicability_constraint is record
      name                   : Unbounded_String;
      result                 : Boolean;
      corresponding_function : applicability_constraint_function;
   end record;

   type applicability_constraint_ptr is access all applicability_constraint;

   procedure initialize (obj : out applicability_constraint);
   procedure put (obj : in applicability_constraint);
   procedure put (obj : in applicability_constraint_ptr);
   function copy
     (obj : in applicability_constraint_ptr)
      return applicability_constraint_ptr;
   function copy
     (obj : in applicability_constraint) return applicability_constraint_ptr;
   procedure build_attributes_xml_string
     (obj    : in     applicability_constraint;
      result : in out Unbounded_String);
   function xml_string
     (obj : in applicability_constraint) return Unbounded_String;
   function xml_string
     (obj : in applicability_constraint_ptr) return Unbounded_String;
   function xml_ref_string
     (obj : in applicability_constraint) return Unbounded_String;
   procedure free is new Unchecked_Deallocation
     (applicability_constraint,
      applicability_constraint_ptr);

   package applicability_constraints_list_package is new access_lists
     (applicability_constraint,
      applicability_constraint_ptr,
      put,
      free,
      copy,
      xml_string);
   use applicability_constraints_list_package;
   subtype applicability_constraints_list is
     applicability_constraints_list_package.list;
   subtype applicability_constraints_list_ptr is
     applicability_constraints_list_package.list_ptr;
   subtype applicability_constraints_list_iterator is
     applicability_constraints_list_package.iterator;
   subtype applicability_constraints_list_iterator_ptr is
     applicability_constraints_list_package.iterator_ptr;

-- --------= Applicability_Constraint_Case =--------

   type applicability_constraint_case is record
      name                      : Unbounded_String;
      feasibility_test_names    : Unbounded_String;
      applicability_constraints : applicability_constraints_list;
   end record;

   type applicability_constraint_case_ptr is
     access all applicability_constraint_case;

   procedure initialize (obj : out applicability_constraint_case);
   procedure put (obj : in applicability_constraint_case);
   procedure put (obj : in applicability_constraint_case_ptr);
   function copy
     (obj : in applicability_constraint_case_ptr)
      return applicability_constraint_case_ptr;
   function copy
     (obj : in applicability_constraint_case)
      return applicability_constraint_case_ptr;
   procedure build_attributes_xml_string
     (obj    : in     applicability_constraint_case;
      result : in out Unbounded_String);
   function xml_string
     (obj : in applicability_constraint_case) return Unbounded_String;
   function xml_string
     (obj : in applicability_constraint_case_ptr) return Unbounded_String;
   function xml_ref_string
     (obj : in applicability_constraint_case) return Unbounded_String;
   procedure free is new Unchecked_Deallocation
     (applicability_constraint_case,
      applicability_constraint_case_ptr);

   package applicability_constraint_cases_list_package is new access_lists
     (applicability_constraint_case,
      applicability_constraint_case_ptr,
      put,
      free,
      copy,
      xml_string);
   use applicability_constraint_cases_list_package;
   subtype applicability_constraint_cases_list is
     applicability_constraint_cases_list_package.list;
   subtype applicability_constraint_cases_list_ptr is
     applicability_constraint_cases_list_package.list_ptr;
   subtype applicability_constraint_cases_list_iterator is
     applicability_constraint_cases_list_package.iterator;
   subtype applicability_constraint_cases_list_iterator_ptr is
     applicability_constraint_cases_list_package.iterator_ptr;

-- --------= All_Cases_Structure =--------

   type all_cases_structure is record
      cases : applicability_constraint_cases_list;
   end record;

   type all_cases_structure_ptr is access all all_cases_structure;

   procedure initialize (obj : out all_cases_structure);
   procedure put (obj : in all_cases_structure);
   procedure put (obj : in all_cases_structure_ptr);
   function copy
     (obj : in all_cases_structure_ptr) return all_cases_structure_ptr;
   function copy (obj : in all_cases_structure) return all_cases_structure_ptr;
   procedure build_attributes_xml_string
     (obj    : in     all_cases_structure;
      result : in out Unbounded_String);
   function xml_string (obj : in all_cases_structure) return Unbounded_String;
   function xml_string
     (obj : in all_cases_structure_ptr) return Unbounded_String;
   function xml_ref_string
     (obj : in all_cases_structure) return Unbounded_String;
   procedure free is new Unchecked_Deallocation
     (all_cases_structure,
      all_cases_structure_ptr);

end applicability_constraints_main_structure;
