------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This Ada package was automatically generated by the software engineering
--tool Platypus
--  see http://cassoulet.univ-brest.fr/mme
--
--  Any modification of this file will be lost.
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model.
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Cheddar is a free real time scheduling tool.
-- This program provides services to automatically check temporal constraints
-- of real time tasks.
--
-- Copyright (C) 2002-2009   Frank Singhoff
-- Cheddar is developed by the LISYC Team, University of Brest
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--      To post to this mailing list, you must be subscribed
--      (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

with Generic_Graph; use Generic_Graph;

with Tasks; use Tasks;

with Buffers; use Buffers;

with Messages; use Messages;

with Dependencies; use Dependencies;

with Resources; use Resources;

with systems; use systems;

with Processors; use Processors;

with convert_strings;

with convert_unbounded_strings;

with Text_IO; use Text_IO;

with Ada.Finalization;

with unbounded_strings; use unbounded_strings;

use unbounded_strings.unbounded_string_list_package;

with Unchecked_Deallocation;

package DP_Graph.extended is

   building_graph_exception : exception;

   procedure initialize (obj : in out task_node_ptr);
   procedure initialize (obj : in out time_triggered_communication_edge_ptr);
   procedure initialize (obj : in out resource_edge_ptr);
   procedure initialize (obj : in out precedence_edge_ptr);
   procedure initialize (obj : in out communication_edge_ptr);
   procedure initialize (obj : in out buffer_edge_ptr);

   procedure add_node
     (obj     : in out graph;
      n       : in     task_node_ptr;
      succeed :    out Boolean);
   function create_node_from_task
     (obj : in generic_task_ptr) return task_node_ptr;

   procedure add_edge
     (obj     : in out graph;
      e       : in     time_triggered_communication_edge_ptr;
      succeed :    out Boolean);
   function build_graph_from_system (obj : system) return graph;
   function get_value (obj : graph_ptr) return graph;

end DP_Graph.extended;
