
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Text_io;
use Text_io;

with unbounded_strings;
use unbounded_strings;

with primitive_xml_strings;
use primitive_xml_strings;

with Scheduling_Analysis;
use Scheduling_Analysis;

with Time_Unit_Events;
use Time_Unit_Events;

use Time_Unit_Events.Time_Unit_Package;



Package Body Multiprocessor_Services_Interface is 
 

-- --------= Scheduling_Result =--------

procedure Initialize(obj : out Scheduling_Result) is 
begin
	obj.scheduling_msg := empty_string;
	obj.has_error := false;
	obj.error_msg := empty_string;
	
	if obj.result /= null then
		Free (obj.result );
	end if;
	obj.result := new Scheduling_Sequence;
	Initialize(obj.result.all);

end Initialize;

procedure Put(obj : in Scheduling_Result) is 
begin
	put("scheduling_msg: "); put(obj.scheduling_msg); put ( "; " );
	put("has_error: "); standards_io.boolean_io.put(obj.has_error); put ( "; " );
	put("error_msg: "); put(obj.error_msg); put ( "; " );
	put("result: "); if obj.result /= null then put(obj.result.all); else put("null"); end if;put ( "; " );
end Put;
 
procedure Put(obj : in Scheduling_Result_Ptr) is
begin
	Put(Obj.All);
end Put;


procedure Build_Attributes_XML_String(obj : in Scheduling_Result; result : in out Unbounded_String) is 
begin
	if (XML_String(obj.scheduling_msg) /= Empty_String) then
		result := result & to_unbounded_string("<scheduling_msg>") & XML_String(obj.scheduling_msg) & to_unbounded_string("</scheduling_msg>");
	end if;
	if (XML_String(obj.has_error) /= Empty_String) then
		result := result & to_unbounded_string("<has_error>") & XML_String(obj.has_error) & to_unbounded_string("</has_error>");
	end if;
	if (XML_String(obj.error_msg) /= Empty_String) then
		result := result & to_unbounded_string("<error_msg>") & XML_String(obj.error_msg) & to_unbounded_string("</error_msg>");
	end if;
	if (XML_String(obj.result) /= Empty_String) then
		result := result & to_unbounded_string("<result>") & XML_String(obj.result) & to_unbounded_string("</result>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in Scheduling_Result) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<scheduling_result>");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</scheduling_result>");
	return (result);
end XML_String;

function XML_String(obj : in Scheduling_Result_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Scheduling_Result) return Unbounded_String is
	result : Unbounded_String;
begin
	raise xml_ref_string_error;
	return to_unbounded_string("");
end XML_Ref_String;

function Copy ( obj : in Scheduling_Result ) return Scheduling_Result_Ptr is
	New_Scheduling_Result : Scheduling_Result_Ptr;
begin
	New_Scheduling_Result := new Scheduling_Result'(obj);
	return (New_Scheduling_Result);
end Copy;

function Copy ( obj : in Scheduling_Result_Ptr ) return Scheduling_Result_Ptr is
begin
	return copy(obj.all);
end Copy;



-- --------= Run_Server =--------

procedure Initialize(obj : in out Run_Server) is 
begin
	initialize(Periodic_Task(obj));
	obj.rate := 0.0;
	obj.core := empty_string;
	obj.executing := false;
	obj.job_capacity := 0;
	obj.job_duration := 0;
	obj.job_release := 0;
	obj.job_deadline := 0;
end Initialize;

function Copy ( obj : in Run_Server ) return Run_Server_Ptr is
	New_Run_Server : Run_Server_Ptr;
begin
	New_Run_Server := new Run_Server'(obj);
	return (New_Run_Server);
end Copy;

function Copy ( obj : in Run_Server_Ptr ) return Run_Server_Ptr is
begin
	return copy(obj.all);
end Copy;

procedure Put(obj : in Run_Server) is 
begin
	put(Periodic_Task(obj));
	put("rate: "); standards_io.double_io.put(obj.rate); put ( "; " );
	put("core: "); put(obj.core); put ( "; " );
	put("executing: "); standards_io.boolean_io.put(obj.executing); put ( "; " );
	put("deadlines: "); put(obj.deadlines); put ( "; " );
	put("periods: "); put(obj.periods); put ( "; " );
	put("job: "); put(obj.job); put ( "; " );
	put("job_capacity: "); standards_io.natural_io.put(obj.job_capacity); put ( "; " );
	put("job_duration: "); standards_io.natural_io.put(obj.job_duration); put ( "; " );
	put("job_release: "); standards_io.natural_io.put(obj.job_release); put ( "; " );
	put("job_deadline: "); standards_io.natural_io.put(obj.job_deadline); put ( "; " );
end Put;
 
procedure Put(obj : in Run_Server_Ptr) is
begin
	Put(Obj.All);
end Put;
 
procedure Put_Name ( obj : in Run_Server_Ptr) is
begin
	Put ( To_String ( Obj.Name ) );
end Put_Name;

function Get_Name (obj : in Run_Server) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function Get_Name (obj : in Run_Server_ptr) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function type_of ( obj : in Run_Server ) return unbounded_string_list is
	list : unbounded_string_list;
	s : unbounded_string_ptr;
begin
	Initialize(list);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.GENERIC_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.NAMED_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("TASKS.GENERIC_TASK");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("TASKS.PERIODIC_TASK");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("MULTIPROCESSOR_SERVICES_INTERFACE.RUN_SERVER");
	Add (list, s);

	return list;
end type_of;

function type_of ( obj : in Run_Server_Ptr ) return unbounded_string_list is
begin
	return type_of(obj.all);
end type_of;


procedure Build_Attributes_XML_String(obj : in Run_Server; result : in out Unbounded_String) is 
begin
	Build_Attributes_XML_String(Periodic_Task(obj), result);
	if (XML_String(obj.rate) /= Empty_String) then
		result := result & to_unbounded_string("<rate>") & XML_String(obj.rate) & to_unbounded_string("</rate>");
	end if;
	if (XML_String(obj.core) /= Empty_String) then
		result := result & to_unbounded_string("<core>") & XML_String(obj.core) & to_unbounded_string("</core>");
	end if;
	if (XML_String(obj.executing) /= Empty_String) then
		result := result & to_unbounded_string("<executing>") & XML_String(obj.executing) & to_unbounded_string("</executing>");
	end if;
	if (XML_String(obj.deadlines) /= Empty_String) then
		result := result & to_unbounded_string("<deadlines>") & XML_String(obj.deadlines) & to_unbounded_string("</deadlines>");
	end if;
	if (XML_String(obj.periods) /= Empty_String) then
		result := result & to_unbounded_string("<periods>") & XML_String(obj.periods) & to_unbounded_string("</periods>");
	end if;
	if (XML_String(obj.job) /= Empty_String) then
		result := result & to_unbounded_string("<job>") & XML_String(obj.job) & to_unbounded_string("</job>");
	end if;
	if (XML_String(obj.job_capacity) /= Empty_String) then
		result := result & to_unbounded_string("<job_capacity>") & XML_String(obj.job_capacity) & to_unbounded_string("</job_capacity>");
	end if;
	if (XML_String(obj.job_duration) /= Empty_String) then
		result := result & to_unbounded_string("<job_duration>") & XML_String(obj.job_duration) & to_unbounded_string("</job_duration>");
	end if;
	if (XML_String(obj.job_release) /= Empty_String) then
		result := result & to_unbounded_string("<job_release>") & XML_String(obj.job_release) & to_unbounded_string("</job_release>");
	end if;
	if (XML_String(obj.job_deadline) /= Empty_String) then
		result := result & to_unbounded_string("<job_deadline>") & XML_String(obj.job_deadline) & to_unbounded_string("</job_deadline>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in Run_Server) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<run_server id=""") & obj.cheddar_private_id & to_unbounded_string(""" >");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</run_server>");
	return (result);
end XML_String;

function XML_String(obj : in Run_Server_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Run_Server) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<run_server ref=""") & obj.cheddar_private_id & to_unbounded_string(""" />");
	return (result);
end XML_Ref_String;

function XML_Ref_String(obj : in Run_Server_Ptr) return Unbounded_String is
begin
	return XML_Ref_String(obj.all);
end XML_Ref_String;




-- --------= Run_Server_Primal =--------

procedure Initialize(obj : in out Run_Server_Primal) is 
begin
	initialize(Run_Server(obj));
end Initialize;

function Copy ( obj : in Run_Server_Primal ) return Run_Server_Ptr is
	New_Run_Server_Primal : Run_Server_Primal_Ptr;
begin
	New_Run_Server_Primal := new Run_Server_Primal'(obj);
	return Run_Server_Ptr(New_Run_Server_Primal);
end Copy;

function Copy ( obj : in Run_Server_Primal_Ptr ) return Run_Server_Ptr is
begin
	return copy(obj.all);
end Copy;

procedure Put(obj : in Run_Server_Primal) is 
begin
	put(Run_Server(obj));
	put("packed_servers: "); put(obj.packed_servers); put ( "; " );
end Put;
 
procedure Put(obj : in Run_Server_Primal_Ptr) is
begin
	Put(Obj.All);
end Put;
 
procedure Put_Name ( obj : in Run_Server_Primal_Ptr) is
begin
	Put ( To_String ( Obj.Name ) );
end Put_Name;

function Get_Name (obj : in Run_Server_Primal) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function Get_Name (obj : in Run_Server_Primal_ptr) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function type_of ( obj : in Run_Server_Primal ) return unbounded_string_list is
	list : unbounded_string_list;
	s : unbounded_string_ptr;
begin
	Initialize(list);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.GENERIC_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.NAMED_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("TASKS.GENERIC_TASK");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("TASKS.PERIODIC_TASK");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("MULTIPROCESSOR_SERVICES_INTERFACE.RUN_SERVER");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("MULTIPROCESSOR_SERVICES_INTERFACE.RUN_SERVER_PRIMAL");
	Add (list, s);

	return list;
end type_of;

function type_of ( obj : in Run_Server_Primal_Ptr ) return unbounded_string_list is
begin
	return type_of(obj.all);
end type_of;


procedure Build_Attributes_XML_String(obj : in Run_Server_Primal; result : in out Unbounded_String) is 
begin
	Build_Attributes_XML_String(Run_Server(obj), result);
	if (XML_String(obj.packed_servers) /= Empty_String) then
		result := result & to_unbounded_string("<packed_servers>") & XML_String(obj.packed_servers) & to_unbounded_string("</packed_servers>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in Run_Server_Primal) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<run_server_primal id=""") & obj.cheddar_private_id & to_unbounded_string(""" >");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</run_server_primal>");
	return (result);
end XML_String;

function XML_String(obj : in Run_Server_Primal_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Run_Server_Primal) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<run_server_primal ref=""") & obj.cheddar_private_id & to_unbounded_string(""" />");
	return (result);
end XML_Ref_String;

function XML_Ref_String(obj : in Run_Server_Primal_Ptr) return Unbounded_String is
begin
	return XML_Ref_String(obj.all);
end XML_Ref_String;




-- --------= Run_Server_Dual =--------

procedure Initialize(obj : in out Run_Server_Dual) is 
begin
	initialize(Run_Server(obj));
end Initialize;

function Copy ( obj : in Run_Server_Dual ) return Run_Server_Ptr is
	New_Run_Server_Dual : Run_Server_Dual_Ptr;
begin
	New_Run_Server_Dual := new Run_Server_Dual'(obj);
	return Run_Server_Ptr(New_Run_Server_Dual);
end Copy;

function Copy ( obj : in Run_Server_Dual_Ptr ) return Run_Server_Ptr is
begin
	return copy(obj.all);
end Copy;

procedure Put(obj : in Run_Server_Dual) is 
begin
	put(Run_Server(obj));
	put("primal_server: "); if obj.primal_server /= null then put(obj.primal_server.all); else put("null"); end if;put ( "; " );
end Put;
 
procedure Put(obj : in Run_Server_Dual_Ptr) is
begin
	Put(Obj.All);
end Put;
 
procedure Put_Name ( obj : in Run_Server_Dual_Ptr) is
begin
	Put ( To_String ( Obj.Name ) );
end Put_Name;

function Get_Name (obj : in Run_Server_Dual) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function Get_Name (obj : in Run_Server_Dual_ptr) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function type_of ( obj : in Run_Server_Dual ) return unbounded_string_list is
	list : unbounded_string_list;
	s : unbounded_string_ptr;
begin
	Initialize(list);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.GENERIC_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.NAMED_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("TASKS.GENERIC_TASK");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("TASKS.PERIODIC_TASK");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("MULTIPROCESSOR_SERVICES_INTERFACE.RUN_SERVER");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("MULTIPROCESSOR_SERVICES_INTERFACE.RUN_SERVER_DUAL");
	Add (list, s);

	return list;
end type_of;

function type_of ( obj : in Run_Server_Dual_Ptr ) return unbounded_string_list is
begin
	return type_of(obj.all);
end type_of;


procedure Build_Attributes_XML_String(obj : in Run_Server_Dual; result : in out Unbounded_String) is 
begin
	Build_Attributes_XML_String(Run_Server(obj), result);
	result := result & to_unbounded_string("<primal_server ref=""") & obj.primal_server.cheddar_private_id & to_unbounded_string(""" />");
end Build_Attributes_XML_String;

function XML_String(obj : in Run_Server_Dual) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<run_server_dual id=""") & obj.cheddar_private_id & to_unbounded_string(""" >");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</run_server_dual>");
	return (result);
end XML_String;

function XML_String(obj : in Run_Server_Dual_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Run_Server_Dual) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<run_server_dual ref=""") & obj.cheddar_private_id & to_unbounded_string(""" />");
	return (result);
end XML_Ref_String;

function XML_Ref_String(obj : in Run_Server_Dual_Ptr) return Unbounded_String is
begin
	return XML_Ref_String(obj.all);
end XML_Ref_String;




End Multiprocessor_Services_Interface;
