
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Convert_Strings;

with Convert_Unbounded_Strings;

with text_io;
use text_io;



Package Simulations is 
 
type Simulation_Type is (
	Simulation_Boolean,
	Simulation_Integer,
	Simulation_Double,
	Simulation_Random,
	Simulation_String,
	Simulation_clock,
	Simulation_Array_Boolean,
	Simulation_Array_Integer,
	Simulation_Array_Double,
	Simulation_Array_Random,
	Simulation_Array_String,
	Simulation_array_clock,
	Simulation_Time_Unit_Array_Boolean,
	Simulation_Time_Unit_Array_Integer,
	Simulation_Time_Unit_Array_Double,
	Simulation_Time_Unit_Array_String);

procedure To_Simulation_Type is
new Convert_Strings(Simulation_Type, Simulation_Boolean);
procedure To_Simulation_Type is
new Convert_Unbounded_Strings(Simulation_Type, Simulation_Boolean);
function XML_String (obj : in Simulation_Type) return Unbounded_String;
function XML_Ref_String (obj : in Simulation_Type) return Unbounded_String;
package Simulation_Type_io is new text_io.enumeration_io(Simulation_Type);
use Simulation_Type_io;



End Simulations;
