------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
--
--  Any modification of this file will be lost.
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model.
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Cheddar is a free real time scheduling tool.
-- This program provides services to automatically check temporal constraints
-- of real time tasks.
--
-- Copyright (C) 2002-2014   Frank Singhoff
-- Cheddar is developed by the LAB-STICC Team, University of Brest
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--      To post to this mailing list, you must be subscribed
--      (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

with Framework_Config; use Framework_Config;

with id_generators; use id_generators;

with Objects; use Objects;

with CFG_Nodes; use CFG_Nodes;

with Text_IO; use Text_IO;

with unbounded_strings; use unbounded_strings;

use unbounded_strings.unbounded_string_list_package;

with convert_strings;

with convert_unbounded_strings;

with Ada.Finalization;

with Unchecked_Deallocation;

with primitive_xml_strings; use primitive_xml_strings;

with tables;

with Ada.Strings.Unbounded.Text_IO; use Ada.Strings.Unbounded.Text_IO;

package cfg_edges is

   type cfg_edge;
   type cfg_edge_ptr is access all cfg_edge'class;

-- --------= CFG_Edge =--------

   type cfg_edge is new named_object with record
      node      : Unbounded_String;
      next_node : Unbounded_String;
   end record;

   procedure initialize (obj : in out cfg_edge);
   procedure put (obj : in cfg_edge);
   procedure put (obj : in cfg_edge_ptr);
   procedure put_name (obj : in cfg_edge_ptr);
   procedure build_attributes_xml_string
     (obj    : in     cfg_edge;
      result : in out Unbounded_String);
   function xml_string (obj : in cfg_edge) return Unbounded_String;
   function xml_string (obj : in cfg_edge_ptr) return Unbounded_String;
   function xml_ref_string (obj : in cfg_edge) return Unbounded_String;
   function xml_ref_string (obj : in cfg_edge_ptr) return Unbounded_String;
   function get_name (obj : in cfg_edge) return Unbounded_String;
   function get_name (obj : in cfg_edge_ptr) return Unbounded_String;
   function copy (obj : in cfg_edge_ptr) return cfg_edge_ptr;
   function copy (obj : in cfg_edge) return cfg_edge_ptr;
   function type_of (obj : in cfg_edge) return unbounded_string_list;
   function type_of (obj : in cfg_edge_ptr) return unbounded_string_list;
   procedure free is new Unchecked_Deallocation (cfg_edge'class, cfg_edge_ptr);

   package cfg_edges_table_package is new tables
     (cfg_edge_ptr,
      Framework_Config.Max_CFG_Edges,
      put,
      xml_string,
      xml_ref_string);
   use cfg_edges_table_package;
   subtype cfg_edges_range is cfg_edges_table_package.table_range;
   subtype cfg_edges_range_ptr is cfg_edges_table_package.table_range_ptr;
   subtype cfg_edges_table is cfg_edges_table_package.table;
   subtype cfg_edges_table_ptr is cfg_edges_table_package.table_ptr;

end cfg_edges;
