
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Text_io;
use Text_io;

with unbounded_strings;
use unbounded_strings;

with CFG_Nodes;
use CFG_Nodes;

use CFG_Nodes.CFG_Nodes_Table_Package;

with CFG_Edges;
use CFG_Edges;

use CFG_Edges.CFG_Edges_Table_Package;



Package Body CFGs is 
 

-- --------= CFG =--------

procedure Initialize(obj : in out CFG) is 
begin
	initialize(Named_Object(obj));
	obj.object_type := CFG_Object_Type;
end Initialize;

function Copy ( obj : in CFG ) return CFG_Ptr is
	New_CFG : CFG_Ptr;
begin
	New_CFG := new CFG'(obj);
	return (New_CFG);
end Copy;

function Copy ( obj : in CFG_Ptr ) return CFG_Ptr is
begin
	return copy(obj.all);
end Copy;

procedure Put(obj : in CFG) is 
begin
	put(Named_Object(obj));
	put("nodes: "); put(obj.nodes); put ( "; " );
	put("edges: "); put(obj.edges); put ( "; " );
end Put;
 
procedure Put(obj : in CFG_Ptr) is
begin
	Put(Obj.All);
end Put;
 
procedure Put_Name ( obj : in CFG_Ptr) is
begin
	Put ( To_String ( Obj.Name ) );
end Put_Name;

function Get_Name (obj : in CFG) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function Get_Name (obj : in CFG_ptr) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function type_of ( obj : in CFG ) return unbounded_string_list is
	list : unbounded_string_list;
	s : unbounded_string_ptr;
begin
	Initialize(list);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.GENERIC_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.NAMED_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("CFGS.CFG");
	Add (list, s);

	return list;
end type_of;

function type_of ( obj : in CFG_Ptr ) return unbounded_string_list is
begin
	return type_of(obj.all);
end type_of;


procedure Build_Attributes_XML_String(obj : in CFG; result : in out Unbounded_String) is 
begin
	Build_Attributes_XML_String(Named_Object(obj), result);
	if (XML_String(obj.nodes) /= Empty_String) then
		result := result & to_unbounded_string("<nodes>") & XML_String(obj.nodes) & to_unbounded_string("</nodes>");
	end if;
	if (XML_String(obj.edges) /= Empty_String) then
		result := result & to_unbounded_string("<edges>") & XML_String(obj.edges) & to_unbounded_string("</edges>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in CFG) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<cfg id=""") & obj.cheddar_private_id & to_unbounded_string(""" >");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</cfg>");
	return (result);
end XML_String;

function XML_String(obj : in CFG_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in CFG) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<cfg ref=""") & obj.cheddar_private_id & to_unbounded_string(""" />");
	return (result);
end XML_Ref_String;

function XML_Ref_String(obj : in CFG_Ptr) return Unbounded_String is
begin
	return XML_Ref_String(obj.all);
end XML_Ref_String;




End CFGs;
