
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Objects;
use Objects;

with CFG_Nodes;
use CFG_Nodes;

use CFG_Nodes.CFG_Nodes_Table_Package;

with CFG_Edges;
use CFG_Edges;

use CFG_Edges.CFG_Edges_Table_Package;

with Ada.Finalization;

with unbounded_strings;
use unbounded_strings;

use unbounded_strings.Unbounded_String_List_Package;

with Unchecked_Deallocation;

with Primitive_XML_Strings;
use Primitive_XML_Strings;



Package CFGs is 
 
type CFG; type CFG_Ptr is access all CFG'Class;



-- --------= CFG =--------

type CFG is new Named_Object with 
record
 nodes : CFG_Nodes_Table;
 edges : CFG_Edges_Table;
end record;

procedure Initialize(obj : in out CFG);
procedure Put(obj : in CFG);
procedure Put(obj : in CFG_Ptr);
procedure Put_Name(obj : in CFG_Ptr);
procedure Build_Attributes_XML_String(obj : in CFG; result : in out Unbounded_String);
function XML_String(obj : in CFG) return Unbounded_String;
function XML_String(obj : in CFG_Ptr) return Unbounded_String;
function XML_Ref_String(obj : in CFG) return Unbounded_String;
function XML_Ref_String(obj : in CFG_Ptr) return Unbounded_String;
function Get_Name (obj : in CFG) return Unbounded_String;
function Get_Name (obj : in CFG_Ptr) return Unbounded_String;
function Copy(obj : in CFG_Ptr) return CFG_Ptr;
function Copy(obj : in CFG) return CFG_Ptr;
function type_of(obj : in CFG) return unbounded_string_list;
function type_of(obj : in CFG_Ptr) return unbounded_string_list;
procedure Free  is new Unchecked_Deallocation (CFG'Class, CFG_Ptr);


End CFGs;
