
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Objects;
use Objects;

with Scheduler_Interface;
use Scheduler_Interface;

with Memories;
use Memories;

with Caches;
use Caches;

with standards_io;
use standards_io;

use standards_io.natural_io;

with Text_io;
use Text_io;

with Unbounded_Strings;
use Unbounded_Strings;

use unbounded_strings.Unbounded_String_List_Package;

with Convert_Strings;

with Convert_Unbounded_Strings;

with Ada.Finalization;

with Unchecked_Deallocation;

with Primitive_XML_Strings;
use Primitive_XML_Strings;

with Tables;

with ada.strings.unbounded.text_io;
use ada.strings.unbounded.text_io;



Package Core_Units is 
 
type Core_Unit; type Core_Unit_Ptr is access all Core_Unit'Class;


type Isa_Type is (
	i386,
	powerpc,
	risc5,
	sparc1,
	sparc2,
	sparc3,
	sparc4,
	sparc5,
	sparc6,
	sparc7,
	sparc8);

procedure To_Isa_Type is
new Convert_Strings(Isa_Type, i386);
procedure To_Isa_Type is
new Convert_Unbounded_Strings(Isa_Type, i386);
function XML_String (obj : in Isa_Type) return Unbounded_String;
function XML_Ref_String (obj : in Isa_Type) return Unbounded_String;
package Isa_Type_io is new text_io.enumeration_io(Isa_Type);
use Isa_Type_io;



-- --------= Core_Unit =--------

type Core_Unit is new Named_Object with 
record
 scheduling : Scheduling_Parameters;
 speed : Natural;
 l1_cache_system_name : Unbounded_String;
 worstcase_perequest_intrabank_memory_interference : Natural;
 worstcase_perequest_interbank_memory_interference : Natural;
 memory_partitions : Memories_Table;
 isa : Isa_Type;
end record;

procedure Initialize(obj : in out Core_Unit);
procedure Put(obj : in Core_Unit);
procedure Put(obj : in Core_Unit_Ptr);
procedure Put_Name(obj : in Core_Unit_Ptr);
procedure Build_Attributes_XML_String(obj : in Core_Unit; result : in out Unbounded_String);
function XML_String(obj : in Core_Unit) return Unbounded_String;
function XML_String(obj : in Core_Unit_Ptr) return Unbounded_String;
function XML_Ref_String(obj : in Core_Unit) return Unbounded_String;
function XML_Ref_String(obj : in Core_Unit_Ptr) return Unbounded_String;
function Get_Name (obj : in Core_Unit) return Unbounded_String;
function Get_Name (obj : in Core_Unit_Ptr) return Unbounded_String;
function Copy(obj : in Core_Unit_Ptr) return Core_Unit_Ptr;
function Copy(obj : in Core_Unit) return Core_Unit_Ptr;
function type_of(obj : in Core_Unit) return unbounded_string_list;
function type_of(obj : in Core_Unit_Ptr) return unbounded_string_list;
procedure Free  is new Unchecked_Deallocation (Core_Unit'Class, Core_Unit_Ptr);

package Core_Units_Table_Package is new Tables(Core_Unit_Ptr, Framework_Config.Max_Core_Units, Put, XML_String, XML_Ref_String);
use Core_Units_Table_Package;
subtype Core_Units_Range is Core_Units_Table_Package.table_range;
subtype Core_Units_Range_Ptr is  Core_Units_Table_Package.table_range_Ptr;
subtype Core_Units_Table is Core_Units_Table_Package.table;
subtype Core_Units_Table_Ptr is  Core_Units_Table_Package.table_Ptr;


End Core_Units;
