
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Text_io;
use Text_io;

with unbounded_strings;
use unbounded_strings;

with primitive_xml_strings;
use primitive_xml_strings;



Package Body Data_Accesses is 
 
function XML_String(obj : in Data_Access_Type) return Unbounded_String is
begin
	return to_unbounded_string(Data_Access_Type'image (obj) );
end XML_String;

function XML_Ref_String (obj : in Data_Access_Type) return Unbounded_String is
begin
	raise xml_ref_string_error;
	return to_unbounded_string("");
end XML_Ref_String;



-- --------= Data_Access =--------

procedure Initialize(obj : in out Data_Access) is 
begin
	initialize(Named_Object(obj));
	obj.Access_Type := Read_Data;
	obj.Memory_Address := 0;
	obj.Time_Constraint_Name := empty_string;
	obj.Size := 0;
	obj.object_type := Data_Access_Object_Type;
end Initialize;

function Copy ( obj : in Data_Access ) return Data_Access_Ptr is
	New_Data_Access : Data_Access_Ptr;
begin
	New_Data_Access := new Data_Access'(obj);
	return (New_Data_Access);
end Copy;

function Copy ( obj : in Data_Access_Ptr ) return Data_Access_Ptr is
begin
	return copy(obj.all);
end Copy;

procedure Put(obj : in Data_Access) is 
begin
	put(Named_Object(obj));
	put("Access_Type: "); put(obj.Access_Type); put ( "; " );
	put("Memory_Address: "); standards_io.natural_io.put(obj.Memory_Address); put ( "; " );
	put("Time_Constraint_Name: "); put(obj.Time_Constraint_Name); put ( "; " );
	put("Size: "); standards_io.natural_io.put(obj.Size); put ( "; " );
end Put;
 
procedure Put(obj : in Data_Access_Ptr) is
begin
	Put(Obj.All);
end Put;
 
procedure Put_Name ( obj : in Data_Access_Ptr) is
begin
	Put ( To_String ( Obj.Name ) );
end Put_Name;

function Get_Name (obj : in Data_Access) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function Get_Name (obj : in Data_Access_ptr) return Unbounded_String is
begin
	return obj.name;
end Get_Name;

function type_of ( obj : in Data_Access ) return unbounded_string_list is
	list : unbounded_string_list;
	s : unbounded_string_ptr;
begin
	Initialize(list);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.GENERIC_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("OBJECTS.NAMED_OBJECT");
	Add (list, s);

	s := new unbounded_string;
	s.all := to_unbounded_string("DATA_ACCESSES.DATA_ACCESS");
	Add (list, s);

	return list;
end type_of;

function type_of ( obj : in Data_Access_Ptr ) return unbounded_string_list is
begin
	return type_of(obj.all);
end type_of;


procedure Build_Attributes_XML_String(obj : in Data_Access; result : in out Unbounded_String) is 
begin
	Build_Attributes_XML_String(Named_Object(obj), result);
	if (XML_String(obj.Access_Type) /= Empty_String) then
		result := result & to_unbounded_string("<access_type>") & XML_String(obj.Access_Type) & to_unbounded_string("</access_type>");
	end if;
	if (XML_String(obj.Memory_Address) /= Empty_String) then
		result := result & to_unbounded_string("<memory_address>") & XML_String(obj.Memory_Address) & to_unbounded_string("</memory_address>");
	end if;
	if (XML_String(obj.Time_Constraint_Name) /= Empty_String) then
		result := result & to_unbounded_string("<time_constraint_name>") & XML_String(obj.Time_Constraint_Name) & to_unbounded_string("</time_constraint_name>");
	end if;
	if (XML_String(obj.Size) /= Empty_String) then
		result := result & to_unbounded_string("<size>") & XML_String(obj.Size) & to_unbounded_string("</size>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in Data_Access) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<data_access id=""") & obj.cheddar_private_id & to_unbounded_string(""" >");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</data_access>");
	return (result);
end XML_String;

function XML_String(obj : in Data_Access_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Data_Access) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<data_access ref=""") & obj.cheddar_private_id & to_unbounded_string(""" />");
	return (result);
end XML_Ref_String;

function XML_Ref_String(obj : in Data_Access_Ptr) return Unbounded_String is
begin
	return XML_Ref_String(obj.all);
end XML_Ref_String;




-- --------= Data_Access_Record =--------

procedure Initialize(obj : out Data_Access_Record) is 
begin
	obj.Access_Type := Read_Data;
	obj.Memory_Address := 0;
	obj.Time_Constraint_Name := empty_string;
	obj.Size := 0;
end Initialize;

procedure Put(obj : in Data_Access_Record) is 
begin
	put("Access_Type: "); put(obj.Access_Type); put ( "; " );
	put("Memory_Address: "); standards_io.natural_io.put(obj.Memory_Address); put ( "; " );
	put("Time_Constraint_Name: "); put(obj.Time_Constraint_Name); put ( "; " );
	put("Size: "); standards_io.natural_io.put(obj.Size); put ( "; " );
end Put;
 
procedure Put(obj : in Data_Access_Record_Ptr) is
begin
	Put(Obj.All);
end Put;


procedure Build_Attributes_XML_String(obj : in Data_Access_Record; result : in out Unbounded_String) is 
begin
	if (XML_String(obj.Access_Type) /= Empty_String) then
		result := result & to_unbounded_string("<access_type>") & XML_String(obj.Access_Type) & to_unbounded_string("</access_type>");
	end if;
	if (XML_String(obj.Memory_Address) /= Empty_String) then
		result := result & to_unbounded_string("<memory_address>") & XML_String(obj.Memory_Address) & to_unbounded_string("</memory_address>");
	end if;
	if (XML_String(obj.Time_Constraint_Name) /= Empty_String) then
		result := result & to_unbounded_string("<time_constraint_name>") & XML_String(obj.Time_Constraint_Name) & to_unbounded_string("</time_constraint_name>");
	end if;
	if (XML_String(obj.Size) /= Empty_String) then
		result := result & to_unbounded_string("<size>") & XML_String(obj.Size) & to_unbounded_string("</size>");
	end if;
end Build_Attributes_XML_String;

function XML_String(obj : in Data_Access_Record) return Unbounded_String is
	result : Unbounded_String;
begin
	result := to_unbounded_string("<data_access_record>");
	Build_Attributes_XML_String(obj, result);
	result := result & to_unbounded_string("</data_access_record>");
	return (result);
end XML_String;

function XML_String(obj : in Data_Access_Record_Ptr) return Unbounded_String is
begin
	if obj /= null then
		return XML_String(obj.all);
	else
		return Empty_String;
	end if;
end XML_String;

function XML_Ref_String(obj : in Data_Access_Record) return Unbounded_String is
	result : Unbounded_String;
begin
	raise xml_ref_string_error;
	return to_unbounded_string("");
end XML_Ref_String;

function Copy ( obj : in Data_Access_Record ) return Data_Access_Record_Ptr is
	New_Data_Access_Record : Data_Access_Record_Ptr;
begin
	New_Data_Access_Record := new Data_Access_Record'(obj);
	return (New_Data_Access_Record);
end Copy;

function Copy ( obj : in Data_Access_Record_Ptr ) return Data_Access_Record_Ptr is
begin
	return copy(obj.all);
end Copy;



End Data_Accesses;
