
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Objects;
use Objects;

with Convert_Strings;

with Convert_Unbounded_Strings;

with text_io;
use text_io;

with standards_io;
use standards_io;

use standards_io.natural_io;

with Unbounded_Strings;
use Unbounded_Strings;

use unbounded_strings.Unbounded_String_List_Package;

with Ada.Finalization;

with Unchecked_Deallocation;

with Primitive_XML_Strings;
use Primitive_XML_Strings;

with Tables;

with ada.strings.unbounded.text_io;
use ada.strings.unbounded.text_io;



Package Data_Accesses is 
 
type Data_Access; type Data_Access_Ptr is access all Data_Access'Class;
type Data_Access_Record; type Data_Access_Record_Ptr is access all Data_Access_Record;


type Data_Access_Type is (
	Read_Data,
	Write_Data);

procedure To_Data_Access_Type is
new Convert_Strings(Data_Access_Type, Read_Data);
procedure To_Data_Access_Type is
new Convert_Unbounded_Strings(Data_Access_Type, Read_Data);
function XML_String (obj : in Data_Access_Type) return Unbounded_String;
function XML_Ref_String (obj : in Data_Access_Type) return Unbounded_String;
package Data_Access_Type_io is new text_io.enumeration_io(Data_Access_Type);
use Data_Access_Type_io;



-- --------= Data_Access =--------

type Data_Access is new Named_Object with 
record
 Access_Type : Data_Access_Type;
 Memory_Address : Natural;
 Time_Constraint_Name : Unbounded_String;
 Size : Natural;
end record;

procedure Initialize(obj : in out Data_Access);
procedure Put(obj : in Data_Access);
procedure Put(obj : in Data_Access_Ptr);
procedure Put_Name(obj : in Data_Access_Ptr);
procedure Build_Attributes_XML_String(obj : in Data_Access; result : in out Unbounded_String);
function XML_String(obj : in Data_Access) return Unbounded_String;
function XML_String(obj : in Data_Access_Ptr) return Unbounded_String;
function XML_Ref_String(obj : in Data_Access) return Unbounded_String;
function XML_Ref_String(obj : in Data_Access_Ptr) return Unbounded_String;
function Get_Name (obj : in Data_Access) return Unbounded_String;
function Get_Name (obj : in Data_Access_Ptr) return Unbounded_String;
function Copy(obj : in Data_Access_Ptr) return Data_Access_Ptr;
function Copy(obj : in Data_Access) return Data_Access_Ptr;
function type_of(obj : in Data_Access) return unbounded_string_list;
function type_of(obj : in Data_Access_Ptr) return unbounded_string_list;
procedure Free  is new Unchecked_Deallocation (Data_Access'Class, Data_Access_Ptr);

package Data_Accesses_Table_Package is new Tables(Data_Access_Ptr, Max_Data_Accesses, Put, XML_String, XML_Ref_String);
use Data_Accesses_Table_Package;
subtype Data_Accesses_Range is Data_Accesses_Table_Package.table_range;
subtype Data_Accesses_Range_Ptr is  Data_Accesses_Table_Package.table_range_Ptr;
subtype Data_Accesses_Table is Data_Accesses_Table_Package.table;
subtype Data_Accesses_Table_Ptr is  Data_Accesses_Table_Package.table_Ptr;


-- --------= Data_Access_Record =--------

type Data_Access_Record is
record
 Access_Type : Data_Access_Type;
 Memory_Address : Natural;
 Time_Constraint_Name : Unbounded_String;
 Size : Natural;
end record;

procedure Initialize(obj : out Data_Access_Record);
procedure Put(obj : in Data_Access_Record);
procedure Put(obj : in Data_Access_Record_Ptr);
function Copy(obj : in Data_Access_Record_Ptr) return Data_Access_Record_Ptr;
function Copy(obj : in Data_Access_Record) return Data_Access_Record_Ptr;
procedure Build_Attributes_XML_String(obj : in Data_Access_Record; result : in out Unbounded_String);
function XML_String(obj : in Data_Access_Record) return Unbounded_String;
function XML_String(obj : in Data_Access_Record_Ptr) return Unbounded_String;
function XML_Ref_String(obj : in Data_Access_Record) return Unbounded_String;
procedure Free  is new Unchecked_Deallocation (Data_Access_Record, Data_Access_Record_Ptr);


End Data_Accesses;
