
------------------------------------------------------------------------------
------------------------------------------------------------------------------
--  This source file was automatically generated by Platypus
--  see http://dossen.univ-brest.fr/apl
-- 
--  Any modification of this file will be lost. 
--  Please see the "platypus" directory instead : it contains the Cheddar's
--  model and its meta-model. 
------------------------------------------------------------------------------
 
------------------------------------------------------------------------------
-- Cheddar is a GNU GPL real-time scheduling analysis tool.
-- This program provides services to automatically check schedulability and
-- other performance criteria of real-time architecture models.
--
-- Copyright (C) 2002-2016   Frank Singhoff, Alain Plantec, Jerome Legrand
--
-- The Cheddar project was started in 2002 by 
-- Frank Singhoff, Lab-STICC UMR 6285 laboratory, Université de Bretagne Occidentale
-- 
-- Cheddar has been published in the "Agence de Protection des Programmes/France" in 2008. 
-- Since 2008, Ellidiss technologies also contributes to the development of 
-- Cheddar and provides industrial support.
--
-- The full list of contributors and sponsors can be found in AUTHORS.txt and SPONSORS.txt
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--
--
-- Contact : cheddar@listes.univ-brest.fr
--   To post to this mailing list, you must be subscribed
--   (see http//beru.univ-brest.fr/~singhoff/cheddar for details)
--
------------------------------------------------------------------------------
------------------------------------------------------------------------------

with Ada.Strings.Unbounded;
use Ada.Strings.Unbounded;

with Framework_Config;
use Framework_Config;

with id_generators;
use id_generators;

with Objects;
use Objects;

with Convert_Strings;

with Convert_Unbounded_Strings;

with text_io;
use text_io;

with standards_io;
use standards_io;

use standards_io.natural_io;

with Ada.Finalization;

with unbounded_strings;
use unbounded_strings;

use unbounded_strings.Unbounded_String_List_Package;

with Unchecked_Deallocation;

with Primitive_XML_Strings;
use Primitive_XML_Strings;

with Tables;



Package Execution_Units is 
 
type Execution_Unit; type Execution_Unit_Ptr is access all Execution_Unit'Class;


type Execution_Unit_Model_Type is (
	LiuLayland_Execution_Unit,
	AADL_Execution_Unit,
	MixedCriticality_Execution_Unit);

procedure To_Execution_Unit_Model_Type is
new Convert_Strings(Execution_Unit_Model_Type, LiuLayland_Execution_Unit);
procedure To_Execution_Unit_Model_Type is
new Convert_Unbounded_Strings(Execution_Unit_Model_Type, LiuLayland_Execution_Unit);
function XML_String (obj : in Execution_Unit_Model_Type) return Unbounded_String;
function XML_Ref_String (obj : in Execution_Unit_Model_Type) return Unbounded_String;
package Execution_Unit_Model_Type_io is new text_io.enumeration_io(Execution_Unit_Model_Type);
use Execution_Unit_Model_Type_io;


type Execution_Unit_Type is (
	Execute_phase,
	Compatible_phase,
	Memory_phase,
	Read_Phase,
	Write_Phase);

procedure To_Execution_Unit_Type is
new Convert_Strings(Execution_Unit_Type, Execute_phase);
procedure To_Execution_Unit_Type is
new Convert_Unbounded_Strings(Execution_Unit_Type, Execute_phase);
function XML_String (obj : in Execution_Unit_Type) return Unbounded_String;
function XML_Ref_String (obj : in Execution_Unit_Type) return Unbounded_String;
package Execution_Unit_Type_io is new text_io.enumeration_io(Execution_Unit_Type);
use Execution_Unit_Type_io;



-- --------= Execution_Unit =--------

type Execution_Unit is new Named_Object with 
record
 Type_eu : Execution_Unit_Type;
 values_eu : Natural;
end record;

procedure Initialize(obj : in out Execution_Unit);
procedure Put(obj : in Execution_Unit);
procedure Put(obj : in Execution_Unit_Ptr);
procedure Put_Name(obj : in Execution_Unit_Ptr);
procedure Build_Attributes_XML_String(obj : in Execution_Unit; result : in out Unbounded_String);
function XML_String(obj : in Execution_Unit) return Unbounded_String;
function XML_String(obj : in Execution_Unit_Ptr) return Unbounded_String;
function XML_Ref_String(obj : in Execution_Unit) return Unbounded_String;
function XML_Ref_String(obj : in Execution_Unit_Ptr) return Unbounded_String;
function Get_Name (obj : in Execution_Unit) return Unbounded_String;
function Get_Name (obj : in Execution_Unit_Ptr) return Unbounded_String;
function Copy(obj : in Execution_Unit_Ptr) return Execution_Unit_Ptr;
function Copy(obj : in Execution_Unit) return Execution_Unit_Ptr;
function type_of(obj : in Execution_Unit) return unbounded_string_list;
function type_of(obj : in Execution_Unit_Ptr) return unbounded_string_list;
procedure Free  is new Unchecked_Deallocation (Execution_Unit'Class, Execution_Unit_Ptr);

package Execution_Units_Table_Package is new Tables(Execution_Unit_Ptr, Max_Execution_Units, Put, XML_String, XML_String);
use Execution_Units_Table_Package;
subtype Execution_Units_Range is Execution_Units_Table_Package.table_range;
subtype Execution_Units_Range_Ptr is  Execution_Units_Table_Package.table_range_Ptr;
subtype Execution_Units_Table is Execution_Units_Table_Package.table;
subtype Execution_Units_Table_Ptr is  Execution_Units_Table_Package.table_Ptr;


End Execution_Units;
