
#ifndef  MONANO_OS_CONFIGURE_H
#define  MONANO_OS_CONFIGURE_H yes

#include "monano_configure.h"

/* Constants to identify/active/deactivate constraints on the execution platform
   RTEMS like configuration constants */

#define CONFIGURE_MONANO_RTEMS48 yes
//define CONFIGURE_MONANO_RTEMS48 

#ifdef CONFIGURE_MONANO_RTEMS48
#define CONFIGURE_MONANO_CHANGE_PRIORITY yes
#define CONFIGURE_MONANO_WEAKENING_PRECEDENCE_CONSTRAINTS yes
#define CONFIGURE_MONANO_INCREASE_PERIOD yes
#define CONFIGURE_MONANO_INCREASE_PROCESSOR_SPEED yes
#define CONFIGURE_MONANO_TASKS_EXECUTION_TIME yes
#define CONFIGURE_MONANO_REDUCE_EXECUTION_TIME yes
#define CONFIGURE_MONANO_DELAY_TASK_EXECUTION yes
#define CONFIGURE_MONANO_SUSPENDED_TASKS yes
#define CONFIGURE_MONANO_MULTICORE yes
#define CONFIGURE_MONANO_EDF_SCHEDULING yes
#define CONFIGURE_MONANO_DM_SCHEDULING yes
#define CONFIGURE_MONANO_NON_PREEMPTIVE_SCHEDULING yes
#define CONFIGURE_MONANO_ASYNCHRONOUS_THREADS yes
#define CONFIGURE_MONANO_SHARED_RESOURCES yes
#define CONFIGURE_MONANO_PRECEDENCE_CONSTRAINTS yes
#define CONFIGURE_MONANO_COMPUTE_ONE_INSTANCE_TASKS_EXECUTION_TIME yes
#define CONFIGURE_MONANO_COMPUTE_MANY_INSTANCE_TASKS_EXECUTION_TIME yes
#endif

#ifdef CONFIGURE_MONANO_LINUX
#define CONFIGURE_MONANO_SUSPENDED_TASKS yes
#define CONFIGURE_MONANO_MULTICORE yes
#define CONFIGURE_MONANO_CHANGE_PRIORITY yes
#define CONFIGURE_MONANO_EDF_SCHEDULING yes
#define CONFIGURE_MONANO_DM_SCHEDULING yes
#define CONFIGURE_MONANO_NON_PREEMPTIVE_SCHEDULING yes
#define CONFIGURE_MONANO_ASYNCHRONOUS_THREADS yes
#define CONFIGURE_MONANO_SHARED_RESOURCES yes
#define CONFIGURE_MONANO_PRECEDENCE_CONSTRAINTS yes
#endif		

#endif

