
#ifndef  MONANO_CONFIGURE_H
#define  MONANO_CONFIGURE_H yes


/* RTEMS like configuration constants */

#define CONFIGURE_MAXIMUM_MONANO_THREAD_NUMBER    			        100
#define CONFIGURE_MAXIMUM_MONANO_THREAD_PRECEDENCIES_NUMBER   		100
#define CONFIGURE_MAXIMUM_MONANO_THREAD_SHARED_RESOURCES_NUMBER		100
#define CONFIGURE_MAXIMUM_MONANO_THREAD_STATIC_CONSTRAINTS		    20
#define CONFIGURE_MAXIMUM_MONANO_THREAD_DYNAMIC_CONSTRAINTS		    20

#endif

